package com.alleyway.bean;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_area.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_area.area_name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_area.area_parent_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer areaParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_area.id
     *
     * @return the value of aw_area.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_area.id
     *
     * @param id the value for aw_area.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_area.area_name
     *
     * @return the value of aw_area.area_name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_area.area_name
     *
     * @param areaName the value for aw_area.area_name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_area.area_parent_id
     *
     * @return the value of aw_area.area_parent_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getAreaParentId() {
        return areaParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_area.area_parent_id
     *
     * @param areaParentId the value for aw_area.area_parent_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setAreaParentId(Integer areaParentId) {
        this.areaParentId = areaParentId;
    }
}