package com.alleyway.bean;

public class Commodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.video_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.numbered
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String numbered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.user_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.price
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.ship_address
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String shipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.sales_month
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer salesMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.sales_sum
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer salesSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.remark
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_commodity.presentation
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String presentation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.id
     *
     * @return the value of aw_commodity.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.id
     *
     * @param id the value for aw_commodity.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.video_id
     *
     * @return the value of aw_commodity.video_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.video_id
     *
     * @param videoId the value for aw_commodity.video_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.numbered
     *
     * @return the value of aw_commodity.numbered
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getNumbered() {
        return numbered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.numbered
     *
     * @param numbered the value for aw_commodity.numbered
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setNumbered(String numbered) {
        this.numbered = numbered == null ? null : numbered.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.user_id
     *
     * @return the value of aw_commodity.user_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.user_id
     *
     * @param userId the value for aw_commodity.user_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.name
     *
     * @return the value of aw_commodity.name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.name
     *
     * @param name the value for aw_commodity.name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.price
     *
     * @return the value of aw_commodity.price
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.price
     *
     * @param price the value for aw_commodity.price
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.ship_address
     *
     * @return the value of aw_commodity.ship_address
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getShipAddress() {
        return shipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.ship_address
     *
     * @param shipAddress the value for aw_commodity.ship_address
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setShipAddress(String shipAddress) {
        this.shipAddress = shipAddress == null ? null : shipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.sales_month
     *
     * @return the value of aw_commodity.sales_month
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getSalesMonth() {
        return salesMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.sales_month
     *
     * @param salesMonth the value for aw_commodity.sales_month
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setSalesMonth(Integer salesMonth) {
        this.salesMonth = salesMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.sales_sum
     *
     * @return the value of aw_commodity.sales_sum
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getSalesSum() {
        return salesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.sales_sum
     *
     * @param salesSum the value for aw_commodity.sales_sum
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setSalesSum(Integer salesSum) {
        this.salesSum = salesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.add_time
     *
     * @return the value of aw_commodity.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.add_time
     *
     * @param addTime the value for aw_commodity.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.remark
     *
     * @return the value of aw_commodity.remark
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.remark
     *
     * @param remark the value for aw_commodity.remark
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_commodity.presentation
     *
     * @return the value of aw_commodity.presentation
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getPresentation() {
        return presentation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_commodity.presentation
     *
     * @param presentation the value for aw_commodity.presentation
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setPresentation(String presentation) {
        this.presentation = presentation == null ? null : presentation.trim();
    }
}