package com.alleyway.bean;

import java.util.ArrayList;
import java.util.List;

public class CommodityCommentImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public CommodityCommentImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Integer value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Integer value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Integer value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Integer value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Integer value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Integer> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Integer> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Integer value1, Integer value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNull() {
            addCriterion("image_path is null");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNotNull() {
            addCriterion("image_path is not null");
            return (Criteria) this;
        }

        public Criteria andImagePathEqualTo(String value) {
            addCriterion("image_path =", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotEqualTo(String value) {
            addCriterion("image_path <>", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThan(String value) {
            addCriterion("image_path >", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("image_path >=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThan(String value) {
            addCriterion("image_path <", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThanOrEqualTo(String value) {
            addCriterion("image_path <=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLike(String value) {
            addCriterion("image_path like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotLike(String value) {
            addCriterion("image_path not like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathIn(List<String> values) {
            addCriterion("image_path in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotIn(List<String> values) {
            addCriterion("image_path not in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathBetween(String value1, String value2) {
            addCriterion("image_path between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotBetween(String value1, String value2) {
            addCriterion("image_path not between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathIsNull() {
            addCriterion("compress_image_path is null");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathIsNotNull() {
            addCriterion("compress_image_path is not null");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathEqualTo(String value) {
            addCriterion("compress_image_path =", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathNotEqualTo(String value) {
            addCriterion("compress_image_path <>", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathGreaterThan(String value) {
            addCriterion("compress_image_path >", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("compress_image_path >=", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathLessThan(String value) {
            addCriterion("compress_image_path <", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathLessThanOrEqualTo(String value) {
            addCriterion("compress_image_path <=", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathLike(String value) {
            addCriterion("compress_image_path like", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathNotLike(String value) {
            addCriterion("compress_image_path not like", value, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathIn(List<String> values) {
            addCriterion("compress_image_path in", values, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathNotIn(List<String> values) {
            addCriterion("compress_image_path not in", values, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathBetween(String value1, String value2) {
            addCriterion("compress_image_path between", value1, value2, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andCompressImagePathNotBetween(String value1, String value2) {
            addCriterion("compress_image_path not between", value1, value2, "compressImagePath");
            return (Criteria) this;
        }

        public Criteria andAddOrderIsNull() {
            addCriterion("add_order is null");
            return (Criteria) this;
        }

        public Criteria andAddOrderIsNotNull() {
            addCriterion("add_order is not null");
            return (Criteria) this;
        }

        public Criteria andAddOrderEqualTo(Integer value) {
            addCriterion("add_order =", value, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderNotEqualTo(Integer value) {
            addCriterion("add_order <>", value, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderGreaterThan(Integer value) {
            addCriterion("add_order >", value, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_order >=", value, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderLessThan(Integer value) {
            addCriterion("add_order <", value, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderLessThanOrEqualTo(Integer value) {
            addCriterion("add_order <=", value, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderIn(List<Integer> values) {
            addCriterion("add_order in", values, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderNotIn(List<Integer> values) {
            addCriterion("add_order not in", values, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderBetween(Integer value1, Integer value2) {
            addCriterion("add_order between", value1, value2, "addOrder");
            return (Criteria) this;
        }

        public Criteria andAddOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("add_order not between", value1, value2, "addOrder");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 09 11:07:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}