package com.alleyway.bean;

public class EmpiricalIncreaseRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_empirical_increase_rule.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_empirical_increase_rule.operation
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_empirical_increase_rule.increase_empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer increaseEmpirica;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_empirical_increase_rule.id
     *
     * @return the value of aw_empirical_increase_rule.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_empirical_increase_rule.id
     *
     * @param id the value for aw_empirical_increase_rule.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_empirical_increase_rule.operation
     *
     * @return the value of aw_empirical_increase_rule.operation
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_empirical_increase_rule.operation
     *
     * @param operation the value for aw_empirical_increase_rule.operation
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_empirical_increase_rule.increase_empirica
     *
     * @return the value of aw_empirical_increase_rule.increase_empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getIncreaseEmpirica() {
        return increaseEmpirica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_empirical_increase_rule.increase_empirica
     *
     * @param increaseEmpirica the value for aw_empirical_increase_rule.increase_empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setIncreaseEmpirica(Integer increaseEmpirica) {
        this.increaseEmpirica = increaseEmpirica;
    }
}