package com.alleyway.bean;

public class EmpiricalRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_empirical_rule.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_empirical_rule.grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_empirical_rule.need_empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer needEmpirica;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_empirical_rule.id
     *
     * @return the value of aw_empirical_rule.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_empirical_rule.id
     *
     * @param id the value for aw_empirical_rule.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_empirical_rule.grade
     *
     * @return the value of aw_empirical_rule.grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_empirical_rule.grade
     *
     * @param grade the value for aw_empirical_rule.grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_empirical_rule.need_empirica
     *
     * @return the value of aw_empirical_rule.need_empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getNeedEmpirica() {
        return needEmpirica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_empirical_rule.need_empirica
     *
     * @param needEmpirica the value for aw_empirical_rule.need_empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setNeedEmpirica(Integer needEmpirica) {
        this.needEmpirica = needEmpirica;
    }
}