package com.alleyway.bean;

public class Reply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_reply.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_reply.comment_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_reply.send_user_nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String sendUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_reply.receive_user_nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String receiveUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_reply.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_reply.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_reply.id
     *
     * @return the value of aw_reply.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_reply.id
     *
     * @param id the value for aw_reply.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_reply.comment_id
     *
     * @return the value of aw_reply.comment_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_reply.comment_id
     *
     * @param commentId the value for aw_reply.comment_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_reply.send_user_nickname
     *
     * @return the value of aw_reply.send_user_nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getSendUserNickname() {
        return sendUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_reply.send_user_nickname
     *
     * @param sendUserNickname the value for aw_reply.send_user_nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setSendUserNickname(String sendUserNickname) {
        this.sendUserNickname = sendUserNickname == null ? null : sendUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_reply.receive_user_nickname
     *
     * @return the value of aw_reply.receive_user_nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getReceiveUserNickname() {
        return receiveUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_reply.receive_user_nickname
     *
     * @param receiveUserNickname the value for aw_reply.receive_user_nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setReceiveUserNickname(String receiveUserNickname) {
        this.receiveUserNickname = receiveUserNickname == null ? null : receiveUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_reply.content
     *
     * @return the value of aw_reply.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_reply.content
     *
     * @param content the value for aw_reply.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_reply.add_time
     *
     * @return the value of aw_reply.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_reply.add_time
     *
     * @param addTime the value for aw_reply.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }
}