package com.alleyway.bean;

import java.util.ArrayList;
import java.util.List;

public class ReplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public ReplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Integer value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Integer value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Integer value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Integer value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Integer value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Integer> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Integer> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Integer value1, Integer value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameIsNull() {
            addCriterion("send_user_nickname is null");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameIsNotNull() {
            addCriterion("send_user_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameEqualTo(String value) {
            addCriterion("send_user_nickname =", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameNotEqualTo(String value) {
            addCriterion("send_user_nickname <>", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameGreaterThan(String value) {
            addCriterion("send_user_nickname >", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("send_user_nickname >=", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameLessThan(String value) {
            addCriterion("send_user_nickname <", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameLessThanOrEqualTo(String value) {
            addCriterion("send_user_nickname <=", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameLike(String value) {
            addCriterion("send_user_nickname like", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameNotLike(String value) {
            addCriterion("send_user_nickname not like", value, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameIn(List<String> values) {
            addCriterion("send_user_nickname in", values, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameNotIn(List<String> values) {
            addCriterion("send_user_nickname not in", values, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameBetween(String value1, String value2) {
            addCriterion("send_user_nickname between", value1, value2, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andSendUserNicknameNotBetween(String value1, String value2) {
            addCriterion("send_user_nickname not between", value1, value2, "sendUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameIsNull() {
            addCriterion("receive_user_nickname is null");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameIsNotNull() {
            addCriterion("receive_user_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameEqualTo(String value) {
            addCriterion("receive_user_nickname =", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameNotEqualTo(String value) {
            addCriterion("receive_user_nickname <>", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameGreaterThan(String value) {
            addCriterion("receive_user_nickname >", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("receive_user_nickname >=", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameLessThan(String value) {
            addCriterion("receive_user_nickname <", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameLessThanOrEqualTo(String value) {
            addCriterion("receive_user_nickname <=", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameLike(String value) {
            addCriterion("receive_user_nickname like", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameNotLike(String value) {
            addCriterion("receive_user_nickname not like", value, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameIn(List<String> values) {
            addCriterion("receive_user_nickname in", values, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameNotIn(List<String> values) {
            addCriterion("receive_user_nickname not in", values, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameBetween(String value1, String value2) {
            addCriterion("receive_user_nickname between", value1, value2, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andReceiveUserNicknameNotBetween(String value1, String value2) {
            addCriterion("receive_user_nickname not between", value1, value2, "receiveUserNickname");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(String value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(String value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(String value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(String value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(String value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(String value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLike(String value) {
            addCriterion("add_time like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotLike(String value) {
            addCriterion("add_time not like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<String> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<String> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(String value1, String value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(String value1, String value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aw_reply
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 09 11:07:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aw_reply
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}