package com.alleyway.bean;

public class RoleTright {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_role_tright.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_role_tright.role_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_role_tright.tright_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer trightId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_role_tright.id
     *
     * @return the value of aw_role_tright.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_role_tright.id
     *
     * @param id the value for aw_role_tright.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_role_tright.role_id
     *
     * @return the value of aw_role_tright.role_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_role_tright.role_id
     *
     * @param roleId the value for aw_role_tright.role_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_role_tright.tright_id
     *
     * @return the value of aw_role_tright.tright_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getTrightId() {
        return trightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_role_tright.tright_id
     *
     * @param trightId the value for aw_role_tright.tright_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setTrightId(Integer trightId) {
        this.trightId = trightId;
    }
}