package com.alleyway.bean;

public class SensitiveWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_sensitive_word.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_sensitive_word.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_sensitive_word.id
     *
     * @return the value of aw_sensitive_word.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_sensitive_word.id
     *
     * @param id the value for aw_sensitive_word.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_sensitive_word.content
     *
     * @return the value of aw_sensitive_word.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_sensitive_word.content
     *
     * @param content the value for aw_sensitive_word.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}