package com.alleyway.bean;

import java.math.BigDecimal;

public class UserGrade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user_grade.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user_grade.user_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user_grade.grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user_grade.empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer empirica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user_grade.percent
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private BigDecimal percent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user_grade.id
     *
     * @return the value of aw_user_grade.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user_grade.id
     *
     * @param id the value for aw_user_grade.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user_grade.user_id
     *
     * @return the value of aw_user_grade.user_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user_grade.user_id
     *
     * @param userId the value for aw_user_grade.user_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user_grade.grade
     *
     * @return the value of aw_user_grade.grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user_grade.grade
     *
     * @param grade the value for aw_user_grade.grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user_grade.empirica
     *
     * @return the value of aw_user_grade.empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getEmpirica() {
        return empirica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user_grade.empirica
     *
     * @param empirica the value for aw_user_grade.empirica
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setEmpirica(Integer empirica) {
        this.empirica = empirica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user_grade.percent
     *
     * @return the value of aw_user_grade.percent
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public BigDecimal getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user_grade.percent
     *
     * @param percent the value for aw_user_grade.percent
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setPercent(BigDecimal percent) {
        this.percent = percent;
    }
}