package com.alleyway.bean;

public class User {

    // 用户经过多表查询出来的头像地址-高清
    private String headPortrait;

    // 用户经过多表查询出来的头像地址-压缩
    private String headPortraitCompress;

    // 用户经过多表查询出来的头像挂件地址
    private String pendant;


    public String getHeadPortrait() {
        return headPortrait;
    }

    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait;
    }

    public String getHeadPortraitCompress() {
        return headPortraitCompress;
    }

    public void setHeadPortraitCompress(String headPortraitCompress) {
        this.headPortraitCompress = headPortraitCompress;
    }

    public String getPendant() {
        return pendant;
    }

    public void setPendant(String pendant) {
        this.pendant = pendant;
    }


    @Override
    public String toString() {
        return "User{" +
	      "headPortrait='" + headPortrait + '\'' +
	      ", headPortraitCompress='" + headPortraitCompress + '\'' +
	      ", pendant='" + pendant + '\'' +
	      ", id=" + id +
	      ", userPhone='" + userPhone + '\'' +
	      ", userName='" + userName + '\'' +
	      ", userPassword='" + userPassword + '\'' +
	      ", nickname='" + nickname + '\'' +
	      ", email='" + email + '\'' +
	      ", gender=" + gender +
	      ", birthday='" + birthday + '\'' +
	      ", userCity='" + userCity + '\'' +
	      ", headPortraitId=" + headPortraitId +
	      ", pendantId=" + pendantId +
	      ", roleId=" + roleId +
	      ", lastLoginTime='" + lastLoginTime + '\'' +
	      ", addTime='" + addTime + '\'' +
	      '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.user_phone
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.user_name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.user_password
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.email
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.gender
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.birthday
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.user_city
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String userCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.head_portrait_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer headPortraitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.pendant_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer pendantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.role_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.last_login_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_user.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.id
     *
     * @return the value of aw_user.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.id
     *
     * @param id the value for aw_user.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.user_phone
     *
     * @return the value of aw_user.user_phone
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.user_phone
     *
     * @param userPhone the value for aw_user.user_phone
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.user_name
     *
     * @return the value of aw_user.user_name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.user_name
     *
     * @param userName the value for aw_user.user_name
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.user_password
     *
     * @return the value of aw_user.user_password
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.user_password
     *
     * @param userPassword the value for aw_user.user_password
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.nickname
     *
     * @return the value of aw_user.nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.nickname
     *
     * @param nickname the value for aw_user.nickname
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.email
     *
     * @return the value of aw_user.email
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.email
     *
     * @param email the value for aw_user.email
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.gender
     *
     * @return the value of aw_user.gender
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.gender
     *
     * @param gender the value for aw_user.gender
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.birthday
     *
     * @return the value of aw_user.birthday
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.birthday
     *
     * @param birthday the value for aw_user.birthday
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.user_city
     *
     * @return the value of aw_user.user_city
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getUserCity() {
        return userCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.user_city
     *
     * @param userCity the value for aw_user.user_city
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setUserCity(String userCity) {
        this.userCity = userCity == null ? null : userCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.head_portrait_id
     *
     * @return the value of aw_user.head_portrait_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getHeadPortraitId() {
        return headPortraitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.head_portrait_id
     *
     * @param headPortraitId the value for aw_user.head_portrait_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setHeadPortraitId(Integer headPortraitId) {
        this.headPortraitId = headPortraitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.pendant_id
     *
     * @return the value of aw_user.pendant_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getPendantId() {
        return pendantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.pendant_id
     *
     * @param pendantId the value for aw_user.pendant_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setPendantId(Integer pendantId) {
        this.pendantId = pendantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.role_id
     *
     * @return the value of aw_user.role_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.role_id
     *
     * @param roleId the value for aw_user.role_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.last_login_time
     *
     * @return the value of aw_user.last_login_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.last_login_time
     *
     * @param lastLoginTime the value for aw_user.last_login_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime == null ? null : lastLoginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_user.add_time
     *
     * @return the value of aw_user.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_user.add_time
     *
     * @param addTime the value for aw_user.add_time
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }
}