package com.alleyway.bean;

public class VideoImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_video_image.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_video_image.video_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_video_image.image_path
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_video_image.compress_image_path
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String compressImagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_video_image.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_video_image.add_order
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    private Integer addOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_video_image.id
     *
     * @return the value of aw_video_image.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_video_image.id
     *
     * @param id the value for aw_video_image.id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_video_image.video_id
     *
     * @return the value of aw_video_image.video_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_video_image.video_id
     *
     * @param videoId the value for aw_video_image.video_id
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_video_image.image_path
     *
     * @return the value of aw_video_image.image_path
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_video_image.image_path
     *
     * @param imagePath the value for aw_video_image.image_path
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_video_image.compress_image_path
     *
     * @return the value of aw_video_image.compress_image_path
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getCompressImagePath() {
        return compressImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_video_image.compress_image_path
     *
     * @param compressImagePath the value for aw_video_image.compress_image_path
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setCompressImagePath(String compressImagePath) {
        this.compressImagePath = compressImagePath == null ? null : compressImagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_video_image.content
     *
     * @return the value of aw_video_image.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_video_image.content
     *
     * @param content the value for aw_video_image.content
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_video_image.add_order
     *
     * @return the value of aw_video_image.add_order
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public Integer getAddOrder() {
        return addOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_video_image.add_order
     *
     * @param addOrder the value for aw_video_image.add_order
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    public void setAddOrder(Integer addOrder) {
        this.addOrder = addOrder;
    }
}