package com.alleyway.bean;

import java.util.List;

public class Works {




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.user_id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.label_id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.title
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.cover_path
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private String coverPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.add_time
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.like_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer likeSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.comment_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer commentSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.collect_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer collectSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.audit_state
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.is_show
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aw_works.content
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.id
     *
     * @return the value of aw_works.id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.id
     *
     * @param id the value for aw_works.id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.user_id
     *
     * @return the value of aw_works.user_id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.user_id
     *
     * @param userId the value for aw_works.user_id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.label_id
     *
     * @return the value of aw_works.label_id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.label_id
     *
     * @param labelId the value for aw_works.label_id
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.title
     *
     * @return the value of aw_works.title
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.title
     *
     * @param title the value for aw_works.title
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.cover_path
     *
     * @return the value of aw_works.cover_path
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public String getCoverPath() {
        return coverPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.cover_path
     *
     * @param coverPath the value for aw_works.cover_path
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setCoverPath(String coverPath) {
        this.coverPath = coverPath == null ? null : coverPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.add_time
     *
     * @return the value of aw_works.add_time
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.add_time
     *
     * @param addTime the value for aw_works.add_time
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.like_size
     *
     * @return the value of aw_works.like_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getLikeSize() {
        return likeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.like_size
     *
     * @param likeSize the value for aw_works.like_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setLikeSize(Integer likeSize) {
        this.likeSize = likeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.comment_size
     *
     * @return the value of aw_works.comment_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getCommentSize() {
        return commentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.comment_size
     *
     * @param commentSize the value for aw_works.comment_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setCommentSize(Integer commentSize) {
        this.commentSize = commentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.collect_size
     *
     * @return the value of aw_works.collect_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getCollectSize() {
        return collectSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.collect_size
     *
     * @param collectSize the value for aw_works.collect_size
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setCollectSize(Integer collectSize) {
        this.collectSize = collectSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.audit_state
     *
     * @return the value of aw_works.audit_state
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.audit_state
     *
     * @param auditState the value for aw_works.audit_state
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setAuditState(Integer auditState) {
        this.auditState = auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.is_show
     *
     * @return the value of aw_works.is_show
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.is_show
     *
     * @param isShow the value for aw_works.is_show
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aw_works.content
     *
     * @return the value of aw_works.content
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aw_works.content
     *
     * @param content the value for aw_works.content
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}