package com.alleyway.dao;

import com.alleyway.bean.CommodityCommentImage;
import com.alleyway.bean.CommodityCommentImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityCommentImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(CommodityCommentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(CommodityCommentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(CommodityCommentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(CommodityCommentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<CommodityCommentImage> selectByExample(CommodityCommentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    CommodityCommentImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommodityCommentImage record, @Param("example") CommodityCommentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") CommodityCommentImage record, @Param("example") CommodityCommentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityCommentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_commodity_comment_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(CommodityCommentImage record);
}