package com.alleyway.dao;

import com.alleyway.bean.EmpiricalRule;
import com.alleyway.bean.EmpiricalRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpiricalRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(EmpiricalRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(EmpiricalRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(EmpiricalRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(EmpiricalRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<EmpiricalRule> selectByExample(EmpiricalRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    EmpiricalRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") EmpiricalRule record, @Param("example") EmpiricalRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") EmpiricalRule record, @Param("example") EmpiricalRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(EmpiricalRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_empirical_rule
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(EmpiricalRule record);
}