package com.alleyway.dao;

import com.alleyway.bean.HeadPortrait;
import com.alleyway.bean.HeadPortraitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HeadPortraitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(HeadPortraitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(HeadPortraitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(HeadPortrait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(HeadPortrait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<HeadPortrait> selectByExample(HeadPortraitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    HeadPortrait selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") HeadPortrait record, @Param("example") HeadPortraitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") HeadPortrait record, @Param("example") HeadPortraitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(HeadPortrait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_head_portrait
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(HeadPortrait record);
}