package com.alleyway.dao;

import com.alleyway.bean.IndexSlideshow;
import com.alleyway.bean.IndexSlideshowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexSlideshowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(IndexSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(IndexSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(IndexSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(IndexSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<IndexSlideshow> selectByExample(IndexSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    IndexSlideshow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndexSlideshow record, @Param("example") IndexSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") IndexSlideshow record, @Param("example") IndexSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(IndexSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_index_slideshow
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(IndexSlideshow record);
}