package com.alleyway.dao;

import com.alleyway.bean.Pendant;
import com.alleyway.bean.PendantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PendantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(PendantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(PendantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(Pendant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(Pendant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<Pendant> selectByExample(PendantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    Pendant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") Pendant record, @Param("example") PendantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") Pendant record, @Param("example") PendantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(Pendant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_pendant
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(Pendant record);
}