package com.alleyway.dao;

import com.alleyway.bean.RoleTright;
import com.alleyway.bean.RoleTrightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleTrightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(RoleTrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(RoleTrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(RoleTright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(RoleTright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<RoleTright> selectByExample(RoleTrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    RoleTright selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleTright record, @Param("example") RoleTrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") RoleTright record, @Param("example") RoleTrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(RoleTright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_role_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(RoleTright record);
}