package com.alleyway.dao;

import com.alleyway.bean.ShoppingTrolley;
import com.alleyway.bean.ShoppingTrolleyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingTrolleyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(ShoppingTrolley record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(ShoppingTrolley record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<ShoppingTrolley> selectByExample(ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    ShoppingTrolley selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShoppingTrolley record, @Param("example") ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") ShoppingTrolley record, @Param("example") ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(ShoppingTrolley record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_shopping_trolley
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(ShoppingTrolley record);
}