package com.alleyway.dao;

import com.alleyway.bean.Tright;
import com.alleyway.bean.TrightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(TrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(TrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(Tright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(Tright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<Tright> selectByExample(TrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    Tright selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tright record, @Param("example") TrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") Tright record, @Param("example") TrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(Tright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_tright
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(Tright record);
}