package com.alleyway.dao;

import com.alleyway.bean.UserGrade;
import com.alleyway.bean.UserGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(UserGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(UserGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(UserGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(UserGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<UserGrade> selectByExample(UserGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    UserGrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserGrade record, @Param("example") UserGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") UserGrade record, @Param("example") UserGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(UserGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user_grade
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(UserGrade record);
}