package com.alleyway.dao;

import com.alleyway.bean.Video;
import com.alleyway.bean.VideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int countByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int deleteByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    List<Video> selectByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    Video selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Video record, @Param("example") VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int updateByExample(@Param("record") Video record, @Param("example") VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video
     *
     * @mbggenerated Wed Jun 12 10:07:47 CST 2019
     */
    int updateByPrimaryKey(Video record);
}