package com.alleyway.dao;

import com.alleyway.bean.VideoLabel;
import com.alleyway.bean.VideoLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int countByExample(VideoLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int deleteByExample(VideoLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int insert(VideoLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int insertSelective(VideoLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    List<VideoLabel> selectByExample(VideoLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    VideoLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") VideoLabel record, @Param("example") VideoLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int updateByExample(@Param("record") VideoLabel record, @Param("example") VideoLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int updateByPrimaryKeySelective(VideoLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_label
     *
     * @mbggenerated Wed Jun 12 09:25:08 CST 2019
     */
    int updateByPrimaryKey(VideoLabel record);
}