package com.alleyway.dao;

import com.alleyway.bean.VideoImage;
import com.alleyway.bean.VideoImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(VideoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(VideoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(VideoImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(VideoImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<VideoImage> selectByExample(VideoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    VideoImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") VideoImage record, @Param("example") VideoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") VideoImage record, @Param("example") VideoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(VideoImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_video_image
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(VideoImage record);
}