package com.alleyway.dao;

import com.alleyway.bean.WorksKeyword;
import com.alleyway.bean.WorksKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorksKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int countByExample(WorksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByExample(WorksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insert(WorksKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int insertSelective(WorksKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    List<WorksKeyword> selectByExample(WorksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    WorksKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") WorksKeyword record, @Param("example") WorksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByExample(@Param("record") WorksKeyword record, @Param("example") WorksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKeySelective(WorksKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_keyword
     *
     * @mbggenerated Sun Jun 09 11:07:37 CST 2019
     */
    int updateByPrimaryKey(WorksKeyword record);
}