package com.alleyway.dao;

import com.alleyway.bean.Works;
import com.alleyway.bean.WorksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int countByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int deleteByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int insert(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int insertSelective(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    List<Works> selectByExampleWithBLOBs(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    List<Works> selectByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    Works selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Works record, @Param("example") WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Works record, @Param("example") WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByExample(@Param("record") Works record, @Param("example") WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByPrimaryKeySelective(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByPrimaryKey(Works record);
}