package com.alleyway.dao;

import com.alleyway.bean.WorksLabel;
import com.alleyway.bean.WorksLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorksLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int countByExample(WorksLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int deleteByExample(WorksLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int insert(WorksLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int insertSelective(WorksLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    List<WorksLabel> selectByExample(WorksLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    WorksLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") WorksLabel record, @Param("example") WorksLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByExample(@Param("record") WorksLabel record, @Param("example") WorksLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByPrimaryKeySelective(WorksLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_works_label
     *
     * @mbggenerated Sun Jun 09 11:29:48 CST 2019
     */
    int updateByPrimaryKey(WorksLabel record);
}